### ISSUE TITLE
Fix example for example provided

### ISSUE THREAD

**Issue by M4NU5** [didix21/mdutils#106]
**Describe the bug**
The sample code provided is broken due to the library not being correctly imported

**Current state**
File in question: **doc** > **source** > **examples** > **[Example_Markdown.md](https://github.com/didix21/mdutils/blob/master/doc/source/examples/Example_Markdown.md)**

`import Mdutils`

**Expected state**
`from mdutils.mdutils import MdUtils`

**Comment by didix21** [comment]
fixed here: https://github.com/didix21/mdutils/pull/107
