### ISSUE TITLE
Write to specified path?

### ISSUE THREAD

**Issue by m1nkeh** [didix21/mdutils#22]
I note this repo hasn’t been updated in over a year.. so not sure if still maintained? Is it possible to write md out to a specific file/path?

I might have a dig through file utils later but I have read the docs and it’s not immediately obvious :)

**Comment by didix21** [comment]
Actually I don't have time to create new features but it is open for the community to contribute.
I didn't test it but It is possible, provided that the path exists. For example, if you have created the directory `duck/Mallard/` then you can write on the `file_name='duck/Mallard/yourMarkDownFile'`.
