### ISSUE TITLE
Table of contents link does not work when headers contain special characters

### ISSUE THREAD

**Issue by rosshug** [didix21/mdutils#36]
Headers in markdown have an anchor which is used for links, format is '#' then the header text converted to lower-case, spaces replaced with hyphens, and special characters removed.  

The Table of Contents in MdUtils has a link to the header by converting to lower-case and replacing spaces with hyphens, but does not remove special characters.  This means that some of the links in the ToC will not work.  

For example I have a header level 2, with text "Unnamed: 41", when I create a ToC the link to this is #unnamed:-41, but should be #unnamed-41, i.e. without the colon. Clicking on the link does not take me to the header section of the document as it should do..

**Comment by didix21** [comment]
Thanks for reporting the bug I will take a look as soon as I can.
