### ISSUE TITLE
Missing .md extension when filename has 'md'

### ISSUE THREAD

**Issue by ndechesne** [didix21/mdutils#37]
**Describe the bug**
When using MarkDown with name set to 'foobar-cmd', then the .md extension is not added. 
It looks like a regression introduced in https://github.com/didix21/mdutils/commit/121cfcbcab10a50a72a168072bf0593e959370b4, see 
if name:
            self.file_name = name if 'md' in name else name + '.md'
       
**To Reproduce**
Any file name with the string 'md' can be used, and the output file will be missing the .md extension.

**Expected behavior**
The .md extension should be added.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux (Arch Linux)

**Additional context**

**Comment by didix21** [comment]
Good catch! You're free to open a PR. If not I will work on it as soon as I can. 
Thank you for reporting it!
