### ISSUE TITLE
Allow creation of Table of Contents with arbitrary depth

### ISSUE THREAD

**Issue by mythWizard** [didix21/mdutils#43]
Currently, `new_table_of_contents` limits the header depth to 2. It may be useful to allow creation of a table of contents with more than 2 levels. For example, being able to create a ToC with labels:
```
Contents
========
- 1
    - 1.1
        - 1.1.1
        - 1.1.2
- 2
    - 2.1
        - 2.1.1
        - 2.1.2
            - 2.1.2a
```
etc.

I have worked on a personal fork and believe it would work. I would be willing to make a pull request if this sounds like a useful feature.

**Comment by didix21** [comment]
Seems fine. Any new feature is welcome!
