### ISSUE TITLE
Can't create a header at level 2 without a parent header of level 1

### ISSUE THREAD

**Issue by groceryheist** [didix21/mdutils#48]
**Describe the bug**
I want a sub-header without a header.  I get an IndexError instead.

**To Reproduce**
`
    doc = MdUtils('test.md','test')
    doc.new_header(level=2, 'test')
`
**Expected behavior**
Successfully add the header to the document.

**Desktop (please complete the following information):**
 - OS: Debian Linux
 - Version 9
- Python 3.8

**Comment by didix21** [comment]
Thank you for reporting the bug. I'm going to take a look as soon as I can.

**Comment by didix21** [comment]
The problem is how table of contents is managed. Change it is not very trivial, so maybe you're better option right now is setting `add_table_of_contents='n'` ->` doc.new_header(level=2, title='test', add_table_of_contents='n')`
