### ISSUE TITLE
Create markdown snippets to be stitched together

### ISSUE THREAD

**Issue by powellquiring** [didix21/mdutils#49]
**Is your feature request related to a problem? Please describe.**
Cool library, thanks.  I'm putting together a web page from a class hierarchy.  Here is a small snippet:
```
@dataclass
class Md_insert_code():
  code: str
  language: str = ""

MdUnion = Union[Md_insert_code]

@dataclass
class Expectation():
  expected: str
  actual: str
  details: list[MdUnion]
```

First objects will be created, Second the md files will be generated.   In the example above a class Md_insert_code is going to be used to capture an eventual call to MdUtils.insert_code(code, language).

**Describe the solution you'd like**
Components of the md document would be represented by object types supplied by the mdutils package.

**Comment by didix21** [comment]
Sorry I'm not sure if understand what feature are you requesting. Do you mean something like a MD parser and provide mark down objects by mdutils?
