### ISSUE TITLE
New Page

### ISSUE THREAD

**Issue by Aretru** [didix21/mdutils#51]
Hi!
Is it possible to create a break and to shift the following content to a new page?
Would give more control about layout.

**Comment by didix21** [comment]
Is going to represent a new file this new page ?

**Comment by Aretru** [comment]
No, same file just a new page

**Comment by didix21** [comment]
Sorry but I'm not aware about the possibility of having new pages in markdown. Can you give more information about it ? And answering your question, mdutils right now isn't supporting such feature.
