### ISSUE TITLE
Can't insert image as new inline image without saving locally

### ISSUE THREAD

**Issue by kristiancanler** [didix21/mdutils#52]
I'm trying to include matplotlib figures I'm creating in the same script that I'm calling MdUtils with. It appears currently that I have to save those figures to a directory, either in PNG or HTML format, and then call those images back with a path in a MdUtils method:

```
matplotlib_figure = matplotlib_figure_maker(df)

plt.savefig('/path/to/image.png')

mdFile.new_paragraph(
    mdFile.new_inline_image(text='', path='/path/to/image.png')
)
```
Is there a way to remove this intermediary step?

**Comment by didix21** [comment]
It's the expected behaviour. So answering your question, there isn't an intermediary step. You must save it from your matplotlib and then tell mdutils where the image is.
