### ISSUE TITLE
Add fontsize increase option for Paragraph

### ISSUE THREAD

**Issue by seenureddy** [didix21/mdutils#54]
**Is your feature request related to a problem? Please describe.**

I want to increase font size for my paragraph, I don't see any option available. I saw an option available to change the font color, I think font-size is the similar option to increase font.  

**Describe the solution you'd like**
```
https://github.com/didix21/mdutils/blob/master/mdutils/mdutils.py#L241

from mdutils.mdutils import MdUtils
md_file = MdUtils(file_name='Example_Markdown',title='Markdown File Example')
md_file.new_paragraph(f"Duration:",  font_size=16)

```

**Comment by didix21** [comment]
As far as I know, Markdown doesn't provide a way for setting font size. Can you give more information about it?
