### ISSUE TITLE
Unwanted line break in link url breaks the link

### ISSUE THREAD

**Issue by dp-dev** [didix21/mdutils#70]
Adding a long link in the markdown file will not work as the link will be splitted at a certain length of characters to break the line into the next one.

Steps to reproduce the behavior: I added a very long link line in the document like this one to experience this error:
```
md_file.new_line(md_file.new_inline_link(link="https://www.rezeptwelt.de/saucendipsbrotaufstriche-rezepte/bbq-sauce-aus-finessen-32015/yqmvpwuf-77b3e-450897-cfcd2-84c8tcgw", text="rezeptwelt.de/saucendipsbrotaufstriche-rezepte/bbq-sauce-aus-finessen-32015/yqmvpwuf-77b3e-450897-cfcd2-84c8tcgw", bold_italics_code='i'))
```

**Expected behavior**
I would expect to have a proper link displayed however the link is not working as the output in the markdown file looks like this with the unwanted line break:
```
[*rezeptwelt.de/saucendipsbrotaufstriche-rezepte/bbq-sauce-aus-
finessen-32015/yqmvpwuf-77b3e-450897-cfcd2-84c8tcgw*](https://www.rezeptwelt.de/saucendipsbrotaufstriche-rezepte/bbq-
sauce-aus-finessen-32015/yqmvpwuf-77b3e-450897-cfcd2-84c8tcgw)
```

**Further information**
 - OS: Windows
 - Version 1.3.1

Would be great if this could be fixed as this is I guess some sort of formatting issue which breaks fully working links.

**Comment by didix21** [comment]
Ouch good catch! I'll try to deal as soon as possible. Thanks for reporting.

**Comment by martinjo** [comment]
This is is a irritating bug. But it can be avoided by specifying wrap_width=0.
md_file.write(md_file.new_inline_image(text='image-text', path='http://...'), wrap_width=0)

**Comment by dp-dev** [comment]
@martinjo, thank you for sharing this - I can confirm that this works and solves this issue for me in the used version.
