### ISSUE TITLE
mkreports package

### ISSUE THREAD

**Issue by hhoeflin** [didix21/mdutils#71]
Hi,

after seeing your project a while back, I was inspired to expand on it a bit using mkdocs. It is still beta and some functionality missing/not stable, but would love any feedback you have.

https://github.com/hhoeflin/mkreports

Just opened an issue as I don't have another way to contact!

**Comment by didix21** [comment]
I'm very happy to know this project has inspired you to contribute to open-source. So seems very interesting. Nice work @hhoeflin. I'll be following it! if you have any doubt or anything I could help you, please don't hesitate to contact.

**Comment by hhoeflin** [comment]
Cool - thanks. I was looking to promote it a bit as well, so if you like it, maybe you could consider mentioning it on the README. Thanks!
