### ISSUE TITLE
DEPRECATION on setup.py

### ISSUE THREAD

**Issue by dmidlo** [didix21/mdutils#80]
pip reports the following warning on install

`DEPRECATION: mdutils is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559`

**Comment by didix21** [comment]
I take note about this! Thanks
