### ISSUE TITLE
MarkDownFile not accepting absolute file path anymore

### ISSUE THREAD

**Issue by KarstenSchaeffer** [didix21/mdutils#81]
**Describe the bug**
With "Modify tests to fix flakiness" MarkDownFile.__init__() has been modified to use os.getcwd() as base directory.
This makes it impossible to specify an absolute path via MdUtils.create_md_file().

**To Reproduce**
```
md_file = mdutils.MdUtils(file_name="<absolute file path>", title="My title")
md_file.create_md_file()
```
leads to 
```
FileNotFoundError: [Errno 2] No such file or directory: '<current directory>/<absolute file path>'
```
**Expected behavior**
MD file is created with given absolute file_name.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 22.04

**Comment by didix21** [comment]
Thanks for reporting the issue I'll check for the problem, I recommend to downgrade to 1.4.0 version.

**Comment by lauritsriple** [comment]
I got the same issue. Downgrading to 1.4.0 solves this temporarily.
